clients/js/src/getInitializeInstructionsForMintExtensions.ts, clients/js/src/index.ts, clients/js/test/_setup.ts, clients/js/test/extensions/confidentialTransfer/updateConfidentialTransferMint.test.ts, clients/js/test/extensions/defaultAccountState/initializeDefaultAccountState.test.ts, clients/js/test/extensions/defaultAccountState/updateDefaultAccountState.test.ts, clients/js/test/extensions/transferFree/transferCheckedWithFee.test.ts
Given an array of extensions, give an array of instructions that should be used when initializing the mint account.
=> Add `getInitializeInstructionsForMintExtensions` helper

clients/js/src/getInitializeInstructionsForExtensions.ts, clients/js/src/index.ts, clients/js/test/_setup.ts, clients/js/test/extensions/defaultAccountState/initializeDefaultAccountState.test.ts, clients/js/test/extensions/memoTransfers/disableMemoTransfers.test.ts, clients/js/test/extensions/memoTransfers/enableMemoTransfers.test.ts, clients/js/test/extensions/reallocate.test.ts, clients/js/test/mintTo.test.ts, clients/js/test/transfer.test.ts
This PR renames the `getInitializeInstructionsForMintExtensions` function to `getPreInitializeInstructionsForMintExtensions` and adds two new helper functions:
- `getPostInitializeInstructionsForMintExtensions` for extensions that needs initializing after the mint account was initialized.
- `getPostInitializeInstructionsForTokenExtensions` for getting initialize instructions for token extensions (which must always be used _after_ the token accounts was initialized).
=> Add more helpers to get init instructions for extensions

clients/js/src/getInitializeInstructionsForExtensions.ts
This extension was missing from the helper function.
=> Add MintCloseAuthority to getInitializeInstructionsForMintExtensions helper

clients/cli/src/config.rs
Extract duplicated config loading code into a new `get_cli_config` function to improve code maintainability and reduce duplication. The function handles loading config from file path or default locations.
- Move common config loading logic into standalone function
- Update new() and new_with_clients_and_ws_url to use shared function
- No functional changes
=> refactor(token/cli): extract duplicate config loading logic

clients/js-legacy/src/extensions/extensionType.ts, clients/js-legacy/src/extensions/index.ts, clients/js-legacy/src/extensions/scaledUiAmount/actions.ts, clients/js-legacy/src/extensions/scaledUiAmount/index.ts, clients/js-legacy/src/extensions/scaledUiAmount/instructions.ts, clients/js-legacy/src/extensions/scaledUiAmount/state.ts, clients/js-legacy/src/instructions/setAuthority.ts, clients/js-legacy/src/instructions/types.ts, clients/js-legacy/test/e2e-2022/scaledUiAmount.test.ts
The scaled ui amount extension has not yet been added to the js-legacy client.
Added the scaled ui amount extension to the js-legacy client.
=> [js-legacy] Add scaled ui amount extension

clients/js-legacy/.gitignore, clients/js-legacy/pnpm-lock.yaml
For some reason, pnpm-lock and yarn.lock were in .gitignore, so the legacy JS client was missing a lockfile.
Update .gitignore and commit the lockfile.
=> js-legacy: Add lockfile

.github/dependabot.yml, .github/workflows/dependabot-auto-merge.yml
The repo has working CI, but no dependabot support.
Add dependabot configuration and an auto-merge job to land changes automatically, similar to all the other repos.
Note: I've added auto-merge / required checks / no force push to the main branch, so this will be safe as soon as it lands
=> CI: Add dependabot and auto-merge job

clients/js-legacy/package.json, clients/js-legacy/pnpm-lock.yaml, clients/js-legacy/src/extensions/confidentialTransfer/actions.ts, clients/js-legacy/src/extensions/confidentialTransfer/elgamal.ts, clients/js-legacy/src/extensions/confidentialTransfer/index.ts, clients/js-legacy/src/extensions/confidentialTransfer/instructions.ts, clients/js-legacy/src/extensions/confidentialTransfer/state.ts, clients/js-legacy/src/extensions/extensionType.ts, clients/js-legacy/src/extensions/index.ts, clients/js-legacy/test/e2e-2022/confidentialTransfer.test.ts
The confidential transfer extension has not been added to the js-legacy client yet.
The confidential transfer extension will be added to the js client in a sequence of PRs. In this PR, the `InitializeMint` and `UpdateMint` instructions are added.
=> [js-legacy] Add confidential transfer `InitializeMint` and `UpdateMint`

clients/js-legacy/src/extensions/transferFee/instructions.ts, clients/js-legacy/src/instructions/initializeMint.ts, clients/js-legacy/src/instructions/initializeMint2.ts, clients/js-legacy/src/instructions/initializeMintCloseAuthority.ts, clients/js-legacy/src/instructions/setAuthority.ts, clients/js-legacy/src/serialization.ts, clients/js-legacy/test/unit/transferfee.test.ts
The JS library encodes and decodes `COption<Pubkey>` improperly. During encoding, it overallocates the instruction data buffer to always include the additional 32 bytes, even when the value is `null`. During decoding, it assumes the worst-case size for the instruction data length.
buffer-layout actually contains the way to do this right, by properly implementing `getSpan` to return an error if it's ever used without a buffer:
https://github.com/solana-labs/buffer-layout/blob/ee6cdb8074265b04c884485bb46738cdbc077e41/src/Layout.ts#L282
So this properly fixes the encoding and decoding at the same time:
* during encoding, overallocate to the worst case, then truncate down
* correctly return an error during `getSpan`
* during decoding, use the input buffer with `getSpan` to dynamically …
=> js-legacy: Fix variable-size encoding of COptionPubkey

clients/cli/src/config.rs
As pointed out in #58, the CLI currently fails when just running `create-account <MINT_ADDRESS>`, because a multisig argument is expected during all commands. Clap v3's version of `values_of` gives an error if the arg is not configured in the command.
This was probably missed during the port over to clap v3.
Do the same thing as elsewhere, and change `values_of` to `try_get_many(...).ok().flatten()`.
This is the last place using `values_of` in the CLI that could fail.
Closes #58
=> cli: Fix multisig parsing

clients/js-legacy/src/extensions/extensionType.ts, clients/js-legacy/src/extensions/index.ts, clients/js-legacy/src/extensions/pausable/actions.ts, clients/js-legacy/src/extensions/pausable/index.ts, clients/js-legacy/src/extensions/pausable/instructions.ts, clients/js-legacy/src/extensions/pausable/state.ts, clients/js-legacy/src/instructions/setAuthority.ts, clients/js-legacy/src/instructions/types.ts, clients/js-legacy/test/e2e-2022/pausable.test.ts
The pausable extension has not yet been added to the js-legacy client.
Added the pausable extension to the js-legacy client.
=> [js-legacy] Add pausable extension

.github/actions/setup/action.yml
The Test Client Rust Legacy job is failing due to running out of disk space on my fork:
https://github.com/joncinque/token-2022/actions/runs/12768125169/job/35587971585
Purge the agent tools cache and all docker images stored on the runner. This should give a lot more space.
=> CI: Purge even more packages

program/src/pod.rs
The downstream agave jobs are failing after the upgrade to Rust 1.84, because the lint for public modules needing documentation is getting tripped.
Mark the test module as `pub(crate)` since it shouldn't be used outside.
=> program: Mark test module as `pub(crate)`

.github/workflows/publish-rust.yml, Cargo.toml, package.json, scripts/cliff.toml, scripts/rust/publish.mjs
The publish script only works with the rust client, but we have many rust packages in the repo that need to be deployed.
Update the publish script to take in a folder, and update the workflow to align with the SPL version, which also generates a changelog.
=> CI: Update rust publish script to work for all packages

.github/workflows/publish-rust.yml
The main branch requires pull requests to make changes, but the publish job needs to push a commit and a tag.
Use the ANZA_TEAM_PAT.
=> CI: Use PAT for publish job

scripts/rust/publish.mjs
The tag names from SPL contained nearly the full name of the package, which made sense because there were many packages. The program-specific repos, however, take a different format, and only keep the basename of the directory. Also, they use `@` to separate the name from the version.
Use the basename and separate with `@`!
=> CI: Update tag name to match the repo

.github/workflows/publish-rust.yml
The publish job isn't working, but it's hard to debug because it takes a long time to run.
Don't run the tests.
=> CI: Disable testing during publish for testing

.github/workflows/publish-rust.yml
Things work now on the auto-publish, but the testing is still disabled.
Re-enable the testing, and fix to reference "main" instead of "master".
=> CI: Re-enable testing

.github/workflows/publish-rust.yml, scripts/rust/publish.mjs
The release name came out slightly gross.
Keep things simple, and have the tool default to the tag name.
=> publish: Use the tag name as the release title

.github/dependabot.yml
Dependabot is only configured for the top-level JS lockfile, but we have two other JS client libraries.
Add their directories to the dependabot configuration.
=> dependabot: Add JS client directories

clients/cli/src/clap_app.rs, clients/cli/src/command.rs, clients/cli/tests/command.rs
The rust legacy cli does not yet have support for the scaled ui amount extension.
Added support for the scaled ui amount extension. 
- I think everything should be straightforward. One exception is how the unix timestamp should be taken in as input and how it should be printed out. Currently, the unix timestamp is just taken in as `i64` and printed out as `i64`. If you have a different suggestion, please let me know.
- The solana account-decoder in the monorepo does not yet have support for the scaled ui amount extension, so I wasn't able to add changes to print out the extension. I can wait until the the extension is supported or I can create an issue for this and then follow-up on a subsequent PR.
=> [rust-legacy-cli] Add scaled ui amount extension

clients/cli/src/clap_app.rs, clients/cli/src/command.rs, clients/cli/tests/command.rs
The rust legacy cli does not yet have support for the pausable extension.
Added support for the pausable extension. I think the changes should be pretty straightforward. However, I realized that the solana account-decoder in the monorepo does not yet have support for the pausable extension, so I wasn't able to add changes to print out the pausable extension. I can wait until the the pausable extension is supported or I can create an issue for this and then follow-up on a subsequent PR.
=> [rust-legacy-cli] Add pausable extension

.github/workflows/publish-js-client.yml, package.json, scripts/js/publish.mjs, scripts/utils.mjs
The repo now contains multiple JS packages, but the publish job only works with one of them.
Update the publish script to get things in line with Rust:
* take in a package path to test
* change testing to work for any JS package
* publish to either `@solana-program` or `@solana` using different org secrets -- we'll need to update this afterwards
* generate a changelog
=> publish: Update JS job for multiple packages

clients/js-legacy/package.json
The newest spl-token JS library wasn't actually built before publishing.
Add a `prepublishOnly` step, similar to the other js client.
Fixes https://github.com/solana-program/token/issues/20
=> js-legacy: Add prepublish step

.github/workflows/main.yml
The Rust crates in this repo adhere to semver, but we don't check that new PRs maintain that in CI.
Enable the disabled semver job in CI.
=> CI: Enable semver check job

program/src/extension/scaled_ui_amount/mod.rs
As pointed out at
https://github.com/anza-xyz/agave/pull/4663#discussion_r1934290625, the current scaling behavior is problematic for money amounts, because it uses the default Rust formatting of "round to nearest, ties to even" when producing a UI amount. This behavior can "overvalue" what's in someone's account.
Floor all conversions to 0 (AKA truncate).
=> scaled-ui: Floor all conversions to 0

program/src/instruction.rs
Although the UI amount <-> amount conversions are clear because they use strings, the underlying math uses floats, which has all of the problems normally associated with floats.
Add warnings about the inner workings of `AmountToUiAmount` and `UiAmountToAmount`.
Fixes #130
=> ui-amount: Add a warning for floating-point math

program/src/extension/transfer_fee/processor.rs, program/src/processor.rs
In the normal `process_transfer`, a decimal option indicates which instruction is being processed, which is hard to read.
Make the different transfer options into an enum for total clarity.
Fixes #132
=> program: Clarify different transfer instruction args

clients/rust-legacy/src/token.rs, clients/rust-legacy/tests/confidential_mint_burn.rs, program/src/extension/confidential_mint_burn/account_info.rs
There is no support for the confidential mint burn extension in the rust-legacy client.
Added support for the confidential mint burn in the rust-legacy client:
[329676c](https://github.com/solana-program/token-2022/pull/168/commits/329676cfe125b70bae4015f4236a465ec842e8c2): Made a couple of relatively small changes in the account info interface:
- When generating the proof needed to rotate ElGamal public key, the new ElGamal keypair is not actually needed for the proof generation. So I fixed this.
- When generating the proof needed for confidential mint, the proof constructor takes in the current supply amount. I updated this so that it takes in a aes key instead, which can be used to decrypt the current supply. This interface seemed more natural and simpler by the consumers of this …
=> [rust-legacy-client] Add confidential mint burn extension

program/src/extension/confidential_mint_burn/mod.rs
Currently, constants `MAXIMUM_DEPOSIT_TRANSFER_AMOUNT` and `PENDING_BALANCE_LO_BIT_LENGTH` exists in the confidential mint burn extension, but these constants are not used. They are also duplicates of the constants that exist for the confidential transfer extension. 
They are relic from a sequence of initial attempts at creating the confidential mint burn. 
Remove the constants.
Fixes https://github.com/solana-program/token-2022/issues/131.
=> [program] Remove unnecessary constants in the confidential mint burn extension

clients/rust-legacy/tests/confidential_mint_burn.rs, confidential-transfer/proof-extraction/src/burn.rs, confidential-transfer/proof-extraction/src/mint.rs, confidential-transfer/proof-generation/src/burn.rs, confidential-transfer/proof-generation/src/encryption.rs, confidential-transfer/proof-generation/src/mint.rs, confidential-transfer/proof-tests/tests/proof_test.rs, program/src/extension/confidential_mint_burn/account_info.rs, program/src/extension/confidential_mint_burn/processor.rs
Auditor ciphertexts for the confidential mint and burn amounts were added to instruction data in https://github.com/solana-labs/solana-program-library/pull/7480. In the processor logic for confidential mint and burn, the auditor ciphertext that is included in the instruction data should be checked whether it corresponds to the auditor ciphertext in the proof data.
Currently, the wrong component of the grouped ciphertext is checked. A grouped ElGamal ciphertext for the confidential mint and confidential burn amounts have the second component correspond to the "auditor" component. However, the third component that corresponds to the confidential "supply" is checked for consistency instead.
A simple fix is to just update the processor logic to check the consistency of the second component of …
=> [program] Re-order confidential mint burn ciphertexts to dest/src, supply, then auditor

program/src/extension/confidential_mint_burn/processor.rs
Currently there is a check missing in the confidential mint processor logic (https://github.com/solana-program/token-2022/issues/127).
A confidential mint proof is generated as follows:
1. The client fetches the current supply and computes the updated supply if a mint were to be processed successfully
2. A zkp is generated with respect to the updated supply
3. Finally, on the program side, the processor computes the updated supply and should check that this updated supply that it computed is actually consistent with what was included in the zkp.
The check in step 3 is currently absent in the confidential mint processor logic.
I added the check.
Fixes https://github.com/solana-program/token-2022/issues/127.
=> [program] Check that new supply in the mint and proof data are consistent

clients/rust-legacy/tests/confidential_mint_burn.rs
The pausable extension was not tested with the confidential mint burn extension in https://github.com/solana-labs/solana-program-library/pull/7562 because the rust client for the confidential mint burn extension was missing at the time.
Now that the client-side code is added, we can add the tests.
=> [rust-legacy-client] Add test for pausable extension and confidential mint and burn

confidential-transfer/proof-extraction/src/burn.rs, confidential-transfer/proof-extraction/src/mint.rs, confidential-transfer/proof-extraction/src/transfer.rs, confidential-transfer/proof-extraction/src/transfer_with_fee.rs, confidential-transfer/proof-extraction/src/withdraw.rs
In the proof extraction logic, `.zip` is used to pair the expected commitments and bit lengths with what were provided in the `BatchedRangeProofContext`. This could be confusing to follow without the background knowledge on `BatchedRangeProofContext`, which always holds exactly 8 Pedersen commitments and 8 bit lengths for which the proof is generated for. (https://github.com/solana-program/token-2022/issues/133)
Remove redundant checks and add clarifying comments about `.zip`.
Fixes https://github.com/solana-program/token-2022/issues/133.
=> [confidential-transfer] Remove unnecessary range proof check and add clarifying comments

clients/rust-legacy/src/token.rs, clients/rust-legacy/tests/confidential_mint_burn.rs, program/src/error.rs, program/src/extension/confidential_mint_burn/instruction.rs, program/src/extension/confidential_mint_burn/mod.rs, program/src/extension/confidential_mint_burn/processor.rs
The confidential mint instruction requires zkp that is generated with respect to the current confidential supply in the mint. However, since a confidential mint instruction, which is instigated by individual account owners, updates the confidential supply, this could lead to a DoS attack where a malicious actor constantly burns small amounts tokens to prevent mint.
More information can be found in https://github.com/solana-program/token-2022/issues/126.
I added a `pending_burn` field to `ConfidentialMintBurn` extension. Whenever a confidential burn instruction is processed, the burn amount is added to the `pending_burn` field in the mint. Then on an instruction `ApplyPendingBurn`, this field is subtracted from the confidential supply.
We have the following changes to the program.
State:
- …
=> [program] Add pending burn field to `ConfidentialMintBurn`

Cargo.toml, clients/cli/Cargo.toml, clients/rust-legacy/Cargo.toml, clients/rust-legacy/transfer-hook-test-programs/downgrade/Cargo.toml, clients/rust-legacy/transfer-hook-test-programs/fail/Cargo.toml, clients/rust-legacy/transfer-hook-test-programs/success/Cargo.toml, clients/rust-legacy/transfer-hook-test-programs/swap-with-fee/Cargo.toml, clients/rust-legacy/transfer-hook-test-programs/swap/Cargo.toml, clients/rust/Cargo.toml, confidential-transfer/ciphertext-arithmetic/Cargo.toml, confidential-transfer/elgamal-registry/Cargo.toml, confidential-transfer/proof-extraction/Cargo.toml, confidential-transfer/proof-generation/Cargo.toml, confidential-transfer/proof-tests/Cargo.toml, program/Cargo.toml
#204 did the hard work of upgrading crates to v2.2 as needed, but some of the dependencies were missed. Also, the tool suite is still on v2.1.
Bump the sdk crates to v2.2.1 and the non-sdk crates to v2.2.0
=> deps: Bump everything else to v2.2

.gitignore, Cargo.lock, program/Cargo.toml, program/src/onchain.rs
== Bug fix ==
At the moment, these helpers are passing in an empty signers slice to `transfer_checked()` and `transfer_checked_with_fee()` to avoid clones. Unfortunately, for multisigs, this improperly adds signer status to the `authority_info` which causes an permissions escalation error for consumers.
This PR does:
- Fixes bug where it passes signers to helpers
- Creates a single internal `_invoke_transfer_internal()` to reduce redundancy between functions & allow dependency injection
- Adds unit tests
=> Multisig support on invoke helpers

Cargo.lock
Unblocks CI/CD by updating the lock file which bumps the deps w/ the reported vuln. Currently failing on main: https://github.com/solana-program/token-2022/actions/runs/13718817426/job/38369465864?pr=253.
=> Cargo update [audit check fix]

program/src/onchain.rs
Follow up from https://github.com/solana-program/token-2022/pull/233
At the moment the `invoke_transfer_checked()` function is indiscriminately adding signed accounts to the CPI instruction. Normally this is fine, but when a transfer hook is involved, a bug is apparent. It mistakenly gets added to the list of accounts and then later again as it's handled by `add_extra_accounts_for_execute_cpi()`.
This PR fixes this bug by parsing multisig accounts specifically versus signed accounts generically.
=> Transfer helper: support signed transfer hooks

clients/js-legacy/src/actions/amountToUiAmount.ts, clients/js-legacy/test/unit/scaledAmount.test.ts
This PR adds better support for the Scaled UI Amount extension in the legacy SPL Token SDK, along with code quality improvements for better readability and maintainability.
- Added utility functions for the Scaled UI Amount extension:
- `amountToUiAmountForScaledUiAmountMintWithoutSimulation` - Converts raw token amounts to UI amounts using the scaling multiplier
- `uiAmountToAmountForScaledUiAmountMintWithoutSimulation` - Converts UI amounts back to raw token amounts
- Enhanced `amountToUiAmountForMintWithoutSimulation` to detect and handle Scaled UI Amount extensions
- Enhanced `uiAmountToAmountForMintWithoutSimulation` to support Scaled UI Amount extensions
- Extracted common constants to improve maintainability
- Added helper functions to reduce code duplication
- Improved variable …
=> [js-legacy] add helpers for scaled ui amount

clients/cli/src/clap_app.rs
Closes #311 
renamed arguments and amended descriptions.
From
```bash
<TOKEN_ACCOUNT_ADDRESS>    The address of the token account to receive withdrawn tokens
```
to
```bash
<FEE_RECIPIENT_ADDRESS>    The address of the token account to receive withdrawn tokens
```
and from
```bash
<ACCOUNT_ADDRESS>...       The token accounts to withdraw from
```
to
```bash
<SOURCE_ADDRESS>...        The token account(s) to withdraw fees from.
```
The `Usage` output has been updated (corrected) from
```bash
USAGE:
spl-token withdraw-withheld-tokens [OPTIONS] <ACCOUNT_ADDRESS|--include-mint> <TOKEN_ACCOUNT_ADDRESS> [--]
```
to
```bash
USAGE:
spl-token withdraw-withheld-tokens [OPTIONS] <FEE_RECIPIENT_ADDRESS> <SOURCE_ADDRESS|--include-mint> [--]
```
Run
```
cargo run -- withdraw-withheld-tokens --help
``` …
=> fix `withdraw-withheld-tokens` CLI subcommand showing wrong order of arguments in 'Usage'

Cargo.lock, clients/cli/Cargo.toml, clients/rust-legacy/Cargo.toml, program/Cargo.toml
All of the SPL deps have finally been upgraded to use the component crates rather than solana-program, but token-2022 still has a transitive dependency on solana-program.
Bump all SPL deps and make the spl-token-2022 crate smaller! This brings down the number of deps built from 188 to 155, and drops the build time from 21s to 18s on my machine.
=> deps: Bump all SPL deps

.github/workflows/main.yml, .github/workflows/publish-rust.yml
The semver checks job has been failing for a long time, because it's running on every single pull request.
Just like the other program repos, move the checks to the publish step
=> CI: Add semver-checks to publish workflow

clients/js-legacy/examples/group.ts, clients/js-legacy/examples/pausable.ts, clients/js-legacy/examples/scaledUiAmount.ts
The group, pausable, and scaled-ui-amount extensions have been in the code for some time, but there aren't any JS examples about how to use them.
Similar to most other examples, add some lines about how to use them with the JS legacy client.
=> js-legacy: Add more examples

.github/workflows/main.yml, confidential-transfer/proof-generation/src/burn.rs, confidential-transfer/proof-generation/src/mint.rs, confidential-transfer/proof-generation/src/transfer.rs, confidential-transfer/proof-generation/src/transfer_with_fee.rs, package.json, program/src/extension/confidential_transfer_fee/processor.rs, rust-toolchain.toml, scripts/rust/build-wasm.mjs
- Introduced conditional compilation for WASM target architecture in burn.rs, mint.rs, transfer.rs, and transfer_with_fee.rs.
- Add a new job in the GitHub Actions workflow to build the `spl-token-2022` codebase for the WASM target architecture.
This should ensure no future regressions.
Fixes #293
=> fix: support builds targeting `wasm32`

Cargo.lock, SECURITY.md, confidential-transfer/elgamal-registry/Cargo.toml, confidential-transfer/elgamal-registry/src/entrypoint.rs
There is no security-txt in the elgamal registry program yet.
This is analogous to https://github.com/solana-program/record/pull/52. I added security-txt and also SECURITY.md for the repo.
=> [elgamal-registry] Add security txt for elgamal-registry and add SECURITY.md

program/src/instruction.rs
Fixes https://github.com/solana-program/token-2022/issues/239
=> fix(instructions): mint_to() & mint_to_checked() arguments

.github/actions/setup/action.yml, .github/workflows/main.yml, rust-toolchain.toml
The wasm build was added as a default additional target, which is only necessary for one CI step.
This means that almost every CI step also ends up downloading the wasm target information. Here's one example:
https://github.com/solana-program/token-2022/actions/runs/14239419386/job/39905681594
* Move the wasm build to a separate CI step, that specifically installs the wasm target.
* Remove the wasm target from the list of default targets
=> CI: Don't make wasm required

program/src/extension/mod.rs
A buffer with 166 bytes is counted as invalid, but a buffer with 167 bytes is ok. This doesn't really make sense, because a buffer with 167 bytes wouldn't have room for the first type in the TLV structure.
Remove the off-by-one-error by changing `<=` to `<`.
NOTE: Since there's currently no situation where it makes sense to have an account with 166 or 167 bytes, this shouldn't have any end-user impact, but it's better for the code to be correct.
=> program: Fix off-by-one error

.github/workflows/publish-rust.yml
The auto-publish job failed for spl-token-client because of some missing system dependencies:
https://github.com/solana-program/token-2022/actions/runs/14783911331/job/41508609680
Also install the CLI deps in the semver and publish steps.
=> CI: Fix auto-publish

clients/js/src/generated/types/authorityType.ts, program/idl.json
This PR updates the on-chain Interface Definition Language (IDL) to explicitly model **authority-related types** and regenerates the ts client to reflect those changes.
1. Added **authorityType**:
-   TransferFeeConfig,
-   WithheldWithdraw,
-   CloseMint,
-   InterestRate,
-   PermanentDelegate,
-   ConfidentialTransferMint,
-   TransferHookProgramId,
-   ConfidentialTransferFeeConfig,
-   MetadataPointer,
-   GroupPointer,
-   GroupMemberPointer,
-   ScaledUiAmount,
-   Pause,
`pnpm generate:clients`
=> Update IDL: Add Authority Types

program/src/processor.rs
Currently there is no mechanism to withdraw excess lamports from mint accounts with no authority. In such scenarios, #404 proposes to allow the mint keypair to withdraw the excess lamports.
This PR updates the `withdraw_excess_lamports` instruction to allow withdraw when the authority is the same as the mint, it is a signer and the mint does not have an authority.
Closes #404
=> Allow withdraw excess lamports from mint without authority

clients/js-legacy/src/actions/amountToUiAmount.ts
Currently, the code uses strict equality (`===`) to compare program IDs with `TOKEN_PROGRAM_ID` and `TOKEN_2022_PROGRAM_ID`. This can lead to false negatives when comparing `PublicKey` instances, as they may have different object references even when representing the same underlying public key data.
Replace the strict equality checks with `PublicKey.equals()` method, which properly compares the underlying public key data rather than object references.
- Updated program ID validation in `amountToUiAmountForMintWithoutSimulation`
- Updated program ID validation in `uiAmountToAmountForMintWithoutSimulation`
- Verified that the changes correctly identify both Token Program and Token-2022 Program IDs
- Confirmed that the validation works with different `PublicKey` instances representing the …
=> [js-legacy] Fix program check in amountToUiAmount helper functions

clients/js/src/amountToUiAmount.ts, clients/js/test/extensions/scaledUiAmountMint/amountToUiAmount.test.ts
This PR adds support for the Scaled UI Amount extension to the js ibrary, enabling conversion between raw token amounts and UI representation based on a configurable multiplier.
- Added `amountToUiAmountForScaledUiAmountMintWithoutSimulation` function to convert raw amounts to UI amounts using a configurable multiplier
- Added `uiAmountToAmountForScaledUiAmountMintWithoutSimulation` function for reverse conversion
- Updated main utility functions to detect and handle mints with the Scaled UI Amount extension
- Improved code organization with clear section headers and extracted common helper functions
- Enhanced documentation throughout the codebase
- Added comprehensive test suite for the Scaled UI Amount extension functionality
- Tests cover basic integer multipliers (2x, 3x) and decimal …
=> Add Support for Scaled UI Amount Extension to JS Library

program/src/extension/confidential_transfer/processor.rs, program/src/extension/mod.rs, program/src/extension/reallocate.rs, program/src/processor.rs
The runtime will no longer allow reallocs without zero-init once https://github.com/anza-xyz/agave/pull/5871 lands, but token-2022 uses it.
Stop using it.
cc @lichtso
=> program: Use realloc with zero-init

.github/workflows/main.yml, program/src/extension/confidential_mint_burn/processor.rs, program/src/extension/confidential_transfer/processor.rs
The program currently doesn't build if the zk-ops feature is disabled.
Fix gating on the imports confidential-mint-burn and confidential-transfer functions on the `zk-ops` feature.
=> program: Properly gate zk-ops feature

Cargo.lock, confidential-transfer/ciphertext-arithmetic/Cargo.toml, confidential-transfer/proof-generation/Cargo.toml, confidential-transfer/proof-tests/Cargo.toml
As noted at #588, version 4.2.0 of curve25519-dalek has been yanked, but this repo is still using that version.
Downgrade the dependency to 4.1.3.
Fixes #588
=> deps: Downgrade curve25519-dalek to 4.1.3

clients/cli/src/clap_app.rs, clients/cli/src/command.rs
Added a spl-token CLI option `--enable-transfer-hook` to enable the transfer-hook extension without setting an initial program id value.
=> cli: Added the option to enable transfer-hook without setting an initial program

confidential-transfer/proof-extraction/src/burn.rs, confidential-transfer/proof-extraction/src/mint.rs, confidential-transfer/proof-extraction/src/transfer.rs, confidential-transfer/proof-generation/src/burn.rs, confidential-transfer/proof-generation/src/mint.rs, confidential-transfer/proof-generation/src/transfer.rs, confidential-transfer/proof-generation/src/transfer_with_fee.rs, confidential-transfer/proof-generation/src/withdraw.rs, scripts/solana.dic
- Added docs in the confidential transfer proof generation logic, which should be pretty straightforward
- Fixed one small logic in the transfer with fee proof generation logic: 
- If the transfer fee is equal to the percentage-calculated fee, then the "claimed" delta fee has to be the value `fee * 10_000 - transfer_amount * bp`. 
- If the transfer fee is equal to the max value, then the "claimed" delta fee basically can be anything as long as it is a positive 16-bit number. In this case, in the current logic, I set the claimed fee to be the fee amount, which satisfies this condition, but can be a little confusing because this is a little arbitrary. In this PR, I set this claimed delta fee to be 0 just for clarity.
=> [confidential-transfer] Add docs and additional comments in the proof generation logic

Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/command.rs
Running `spl-token create-token --program-2022 --transfer-hook 11111111111111111111111111111111`  would error out, when its expected to be a valid value that represents the lack of a transfer-hook program. This PR fixes this.
=> Fixed --transfer-hook CLI option not allowing default Pubkey as value

Cargo.lock
The repo is using v0.3.19 of tracing-susbcriber, which has a security advisory.
Bump tracing-subscriber to v0.3.20.
NOTE: There's an extra version fix, nothing to worry about there.
=> audit: Update tracing-subscriber to v0.3.20

confidential/proof-extraction/src/transfer_with_fee.rs
The comments regarding the bit-length in range proofs used in transfer-with-fee was not updated in https://github.com/solana-program/token-2022/pull/512. A new net transfer amount bit length was added and the delta and complement delta bit lengths have been updated to 16 bits from 48 bits.
I fixed these comments.
=> [confidential-transfer] Fix bit-length comments

confidential/proof-generation/src/lib.rs
The function `try_combine_lo_hi_u64` contains logic error. The intended behavior is to shift `amount_hi` with the bit-length and add it with `amount_lo`.
The function is actually not used anywhere in the crate and I think we just missed removing this function during refactoring. This is why this function did not affect the tests.
I considered fixing this function, but since it is not used anywhere in the crate, I thought it would actually be best to just remove it. The current crate version is v0.5.0, so I deprecated the function for v0.6.0.
=> [confidential-transfer] Deprecate `try_combine_lo_hi_u64` function

program/src/extension/confidential_mint_burn/account_info.rs, program/src/extension/confidential_transfer/processor.rs, program/src/extension/confidential_transfer_fee/account_info.rs, program/src/extension/confidential_transfer_fee/processor.rs
Some of the error codes in the program are not precise and can be replaced by a more suitable error variant.
Fixed these error variants.
=> [program] Improve error messages associated with confidential transfer

program/src/extension/confidential_transfer/account_info.rs, program/src/extension/confidential_transfer/verify_proof.rs
Fixing some minor typos related to the withdraw instruction in the program.
=> [program] Fix minor typos related to the confidential transfer withdraw instruction

program/src/extension/confidential_transfer_fee/processor.rs
Currently, in the confidential transfer logic, the summation of fee ciphertexts happens before some of the basic account checks. If some of the basic account checks fail, then the expensive summation of ciphertexts is rendered unnecessary.
I reordered the logic so that some of basic account checks happen before the summation of the ciphertexts.
=> [program] Reorder confidential transfer fee harvest logic to terminate early when possible
